name: admin
description: Funzionalità lato admin
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../shared/core
  ui:
    path: ../../shared/ui
