name: your_turn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_appauth: ^9.0.1
  flutter_riverpod: ^2.4.0
  go_router: ^16.1.0
  graphql_flutter: ^5.1.2
  pdf: ^3.10.7
  printing: ^5.11.0
  provider: ^6.0.5
  google_sign_in: ^6.2.1
  intl: 0.20.2
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^6.0.0
  flutter_lints: ^6.0.0
  flutter_svg: ^2.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/g-logo.png
  
  # Font fallback sicuri per evitare errori Noto
  fonts:
    - family: SafeFont
      fonts:
        - asset: packages/flutter/lib/fonts/Roboto-Regular.ttf
