name: your_turn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2


  flutter_appauth: ^9.0.1
  google_sign_in: ^6.2.1
  graphql_flutter: ^5.1.2
  http: ^1.5.0
  flutter_dotenv: ^6.0.0


  flutter_riverpod: ^2.4.0
  provider: ^6.0.5
  go_router: ^16.1.0
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.7


  pdf: ^3.10.7
  printing: ^5.11.0
  flutter_gen: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  melos: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/g-logo.png
    - .env
