import 'package:your_turn/src/models/roommate.dart';
import 'package:your_turn/src/models/todo_item.dart';
import 'package:your_turn/src/models/todo_status.dart';
import 'package:your_turn/src/models/todo_category.dart';
import 'package:your_turn/src/models/money_tx.dart';



/// Coinquilini finti con foto profilo carine e colorate
final mockRoommates = <Roommate>[
  Roommate(id: "u1", name: "Ale", photoUrl: 'https://api.dicebear.com/7.x/adventurer/png?seed=Ale&backgroundColor=ffdfbf,c0aede,d1d4f9&scale=80', monthlyBudget: 200, tasksCompleted: 8),
  Roommate(id: "u2", name: "Marco", photoUrl: 'https://api.dicebear.com/7.x/adventurer/png?seed=Marco&backgroundColor=ffd5dc,ffdfbf,c0aede&scale=80', monthlyBudget: 150, tasksCompleted: 5),
  Roommate(id: "u3", name: "Giulia", photoUrl: 'https://api.dicebear.com/7.x/adventurer/png?seed=Giulia&backgroundColor=d1d4f9,ffd5dc,b6e3f4&scale=80', monthlyBudget: 180, tasksCompleted: 6),
  Roommate(id: "u4", name: "Luca", photoUrl: 'https://api.dicebear.com/7.x/adventurer/png?seed=Luca&backgroundColor=c0aede,ffdfbf,d1d4f9&scale=80', monthlyBudget: 120, tasksCompleted: 4),
  Roommate(id: "u5", name: "Sofia", photoUrl: 'https://api.dicebear.com/7.x/adventurer/png?seed=Sofia&backgroundColor=ffd5dc,b6e3f4,ffdfbf&scale=80', monthlyBudget: 160, tasksCompleted: 7),
];
/// To-do finti con categorie (date realistiche: ago–ott 2025)
final mockTodos = <TodoItem>[
  TodoItem(
    id: "t1",
    title: "Fare la spesa 🛒",
    notes: "Latte, pane, uova",
    assigneeIds: ["u1", "u2"],
    creatorId: "u1",
    cost: 20,
    status: TodoStatus.done,
    createdAt: DateTime(2025, 8, 17, 10, 15),
    completedAt: DateTime(2025, 8, 17, 11, 05),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'spesa'),
      stockCategories.firstWhere((c) => c.id == 'varie'),
    ],
  ),
  TodoItem(
    id: "t2",
    title: "Pulire la cucina ✨",
    notes: "Attento ai fornelli!",
    assigneeIds: ["u3", "u5"],
    creatorId: "u2",
    cost: 5,
    status: TodoStatus.done,
    createdAt: DateTime(2025, 8, 24, 16, 00),
    completedAt: DateTime(2025, 8, 24, 17, 10),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'spesa'),
      stockCategories.firstWhere((c) => c.id == 'bollette'),
      stockCategories.firstWhere((c) => c.id == 'divertimento'),
      stockCategories.firstWhere((c) => c.id == 'cucina'),
    ],
  ),
  TodoItem(
    id: "t3",
    title: "Pagare bolletta luce 💡",
    assigneeIds: ["u1"],
    creatorId: "u3",
    cost: 90,
    status: TodoStatus.done,
    createdAt: DateTime(2025, 9, 28, 20, 20),
    completedAt: DateTime(2025, 9, 28, 20, 45),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'bollette'),
      stockCategories.firstWhere((c) => c.id == 'manutenzione'),
    ],
  ),
  TodoItem(
    id: "t4",
    title: "Organizzare aperitivo 🍻",
    notes: "Con i vicini di casa",
    assigneeIds: ["u1", "u3", "u4"],
    creatorId: "u4",
    cost: 25,
    status: TodoStatus.done,
    createdAt: DateTime(2025, 8, 30, 18, 30),
    completedAt: DateTime(2025, 8, 30, 22, 15),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'divertimento'),
      stockCategories.firstWhere((c) => c.id == 'spesa'),
      stockCategories.firstWhere((c) => c.id == 'cucina'),
    ],
  ),
  TodoItem(
    id: "t5",
    title: "Riparare rubinetto bagno 🔧",
    notes: "Perde da due giorni",
    assigneeIds: ["u2"],
    creatorId: "u5",
    cost: 30,
    status: TodoStatus.done,
    createdAt: DateTime(2025, 9, 2, 15, 10),
    completedAt: DateTime(2025, 9, 2, 16, 00),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'manutenzione'),
      stockCategories.firstWhere((c) => c.id == 'varie'),
    ],
  ),
  TodoItem(
    id: "t6",
    title: "Comprare ingredienti pizza 🍕",
    notes: "Mozzarella, pomodoro, basilico",
    assigneeIds: ["u2", "u4"],
    creatorId: "u1",
    cost: 15,
    status: TodoStatus.done,
    createdAt: DateTime(2025, 9, 7, 10, 40),
    completedAt: DateTime(2025, 9, 7, 11, 30),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'spesa'),
      stockCategories.firstWhere((c) => c.id == 'cucina'),
    ],
  ),
  TodoItem(
    id: "t7",
    title: "Pagare bolletta gas 🔥",
    assigneeIds: ["u1"],
    creatorId: "u2",
    cost: 60,
    status: TodoStatus.done,
    createdAt: DateTime(2025, 9, 15, 21, 05),
    completedAt: DateTime(2025, 9, 15, 21, 20),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'bollette'),
      stockCategories.firstWhere((c) => c.id == 'manutenzione'),
    ],
  ),
  TodoItem(
    id: "t8",
    title: "Riparare lavastoviglie 🔧",
    notes: "Filtro intasato",
    assigneeIds: ["u2", "u5"],
    creatorId: "u3",
    cost: 30,
    status: TodoStatus.done,
    createdAt: DateTime(2025, 8, 20, 14, 15),
    completedAt: DateTime(2025, 8, 20, 15, 00),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'manutenzione'),
      stockCategories.firstWhere((c) => c.id == 'cucina'),
    ],
  ),
  TodoItem(
    id: "t9",
    title: "Riparare rubinetto bagno 🔧",
    notes: "Gocciola di nuovo, forse guarnizione",
    assigneeIds: ["u2"],
    creatorId: "u4",
    cost: 12,
    status: TodoStatus.open,
    createdAt: DateTime(2025, 10, 12, 18, 25),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'manutenzione'),
      stockCategories.firstWhere((c) => c.id == 'varie'),
    ],
  ),
  TodoItem(
    id: "t10",
    title: "Organizzare cena con amici 🎉",
    notes: "Sabato sera, preparare tutto",
    assigneeIds: ["u1", "u3", "u5"],
    creatorId: "u5",
    cost: 35,
    status: TodoStatus.done,
    createdAt: DateTime(2025, 10, 11, 13, 45),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'divertimento'),
      stockCategories.firstWhere((c) => c.id == 'cucina'),
      stockCategories.firstWhere((c) => c.id == 'spesa'),
    ],
  ),
  TodoItem(
    id: "t11",
    title: "Lavare i piatti 🍽️",
    assigneeIds: ["u2"],
    creatorId: "u1",
    cost: 3,
    status: TodoStatus.open,
    createdAt: DateTime(2025, 10, 14, 12, 20),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'spesa'),
      stockCategories.firstWhere((c) => c.id == 'bollette'),
      stockCategories.firstWhere((c) => c.id == 'divertimento'),
      stockCategories.firstWhere((c) => c.id == 'cucina'),
    ],
  ),
  TodoItem(
    id: "t12",
    title: "Buttare la spazzatura 🗑️",
    assigneeIds: ["u3"],
    creatorId: "u2",
    cost: 2,
    status: TodoStatus.open,
    createdAt: DateTime(2025, 10, 14, 19, 10),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'spesa'),
      stockCategories.firstWhere((c) => c.id == 'bollette'),
      stockCategories.firstWhere((c) => c.id == 'divertimento'),
      stockCategories.firstWhere((c) => c.id == 'varie'),
    ],
  ),
  TodoItem(
    id: "t13",
    title: "Pagare bolletta gas 🔥",
    assigneeIds: ["u1"],
    creatorId: "u3",
    cost: 60,
    status: TodoStatus.open,
    createdAt: DateTime(2025, 10, 9, 21, 30),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'bollette'),
      stockCategories.firstWhere((c) => c.id == 'manutenzione'),
    ],
  ),
  TodoItem(
    id: "t14",
    title: "Pulire il bagno 🚽",
    assigneeIds: ["u2", "u4"],
    creatorId: "u4",
    cost: 8,
    status: TodoStatus.done,
    createdAt: DateTime(2025, 10, 13, 10, 05),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'bollette'),
      stockCategories.firstWhere((c) => c.id == 'manutenzione'),
    ],
  ),
  TodoItem(
    id: "t15",
    title: "Fare la lavatrice 👕",
    assigneeIds: ["u3"],
    creatorId: "u5",
    cost: 4,
    status: TodoStatus.open,
    createdAt: DateTime(2025, 10, 14, 8, 35),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'bollette'),
      stockCategories.firstWhere((c) => c.id == 'varie'),
    ],
  ),
  TodoItem(
    id: "t16",
    title: "Pagare affitto 🏠",
    assigneeIds: ["u1", "u2", "u3", "u4", "u5"],
    creatorId: "u1",
    cost: 900,
    status: TodoStatus.open,
    createdAt: DateTime(2025, 10, 1, 20, 00),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'bollette'),
      stockCategories.firstWhere((c) => c.id == 'varie'),
    ],
  ),
  TodoItem(
    id: "t17",
    title: "Comprare carta igienica 🧻",
    assigneeIds: ["u2"],
    creatorId: "u2",
    cost: 5,
    status: TodoStatus.done,
    createdAt: DateTime(2025, 10, 14, 17, 20),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'spesa'),
      stockCategories.firstWhere((c) => c.id == 'varie'),
    ],
  ),
  TodoItem(
    id: "t18",
    title: "Pulire balcone 🌿",
    assigneeIds: ["u3"],
    creatorId: "u3",
    cost: 6,
    status: TodoStatus.done,
    createdAt: DateTime(2025, 8, 18, 11, 10),
    completedAt: DateTime(2025, 8, 18, 12, 00),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'bollette'),
      stockCategories.firstWhere((c) => c.id == 'varie'),
    ],
  ),
  TodoItem(
    id: "t19",
    title: "Pagare bolletta acqua 🚰",
    assigneeIds: ["u1"],
    creatorId: "u4",
    cost: 40,
    status: TodoStatus.done,
    createdAt: DateTime(2025, 9, 26, 21, 10),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'bollette'),
      stockCategories.firstWhere((c) => c.id == 'manutenzione'),
    ],
  ),
  TodoItem(
    id: "t20",
    title: "Organizzare serata film 🎬",
    assigneeIds: ["u2", "u3", "u4"],
    creatorId: "u5",
    cost: 18,
    status: TodoStatus.open,
    createdAt: DateTime(2025, 10, 11, 21, 00),
    categories: [
      stockCategories.firstWhere((c) => c.id == 'divertimento'),
      stockCategories.firstWhere((c) => c.id == 'varie'),
    ],
  ),
];

final mockTransactions = <MoneyTx>[
  MoneyTx(
    id: "x1",
    roommateId: "u1",
    amount: -45,
    note: "Quota bolletta luce e acqua",
    createdAt: DateTime(2025, 9, 28, 21, 00),
    category: [
      stockCategories.firstWhere((c) => c.id == 'bollette'),
      stockCategories.firstWhere((c) => c.id == 'varie'),
    ],
  ),
  MoneyTx(
    id: "x2",
    roommateId: "u2",
    amount: -10,
    note: "Spesa condivisa per pizza fatta in casa",
    createdAt: DateTime(2025, 9, 7, 12, 00),
    category: [
      stockCategories.firstWhere((c) => c.id == 'spesa'),
      stockCategories.firstWhere((c) => c.id == 'bollette'),
      stockCategories.firstWhere((c) => c.id == 'divertimento'),
    ],
  ),
  MoneyTx(
    id: "x3",
    roommateId: "u3",
    amount: 30,
    note: "Rimborso anticipo cena",
    createdAt: DateTime(2025, 10, 13, 16, 20),
    category: [
      stockCategories.firstWhere((c) => c.id == 'divertimento'),
    ],
  ),
  MoneyTx(
    id: "x4",
    roommateId: "u1",
    amount: -250,
    note: "Affitto mensile ottobre",
    createdAt: DateTime(2025, 10, 1, 10, 00),
    category: [
      stockCategories.firstWhere((c) => c.id == 'manutenzione'),
    ],
  ),
  MoneyTx(
    id: "x5",
    roommateId: "u2",
    amount: -18,
    note: "Biglietti autobus e metro",
    createdAt: DateTime(2025, 10, 10, 8, 45),
    category: [
      stockCategories.firstWhere((c) => c.id == 'varie'),
    ],
  ),
  MoneyTx(
    id: "x6",
    roommateId: "u3",
    amount: -12,
    note: "Detersivi e spugne cucina",
    createdAt: DateTime(2025, 10, 5, 17, 30),
    category: [
      stockCategories.firstWhere((c) => c.id == 'pulizie'),
      stockCategories.firstWhere((c) => c.id == 'spesa'),
    ],
  ),
  MoneyTx(
    id: "x7",
    roommateId: "u1",
    amount: 15,
    note: "Rimborso extra pulizie",
    createdAt: DateTime(2025, 10, 15, 19, 10),
    category: [
      stockCategories.firstWhere((c) => c.id == 'varie'),
      stockCategories.firstWhere((c) => c.id == 'pulizie'),
    ],
  ),
];
